keepyourfriendsclose/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'keepyourfriendsclose'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
    
    url(r'^login/$', views.UserFormView.as_view(), name='login'),
    
    url(r'^auth/$', views.UserFormView.as_view(), name='auth'),
    
    url(r'^logout/$', views.UserFormView.as_view(), name='logout'),
    
    url(r'^loggedin/$', views.UserFormView.as_view(), name='loggedin'),
    
    url(r'^invalid/$', views.UserFormView.as_view(), name='invalid'),
    
    url(r'^$', views.HomeView.as_view(), name='home'),
    
    url(r'^movie/', include('movie.urls')),
    
    url(r'^song/', include('song.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movie/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "movie"

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'movie/add/$', views.MovieCreate.as_view(), name='movie-add'),
    url(r'movie/(?P<pk>[0-9]+)/$', views.MovieUpdate.as_view(), name='movie-update'),
    url(r'movie/(?P<pk>[0-9]+)/delete/$', views.MovieDelete.as_view(), name='movie-delete'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)

song/urls.py
from django.conf.urls import url
from . import views

app_name = "song"

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='home'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'song/add/$', views.SongCreate.as_view(), name='song-add'),
    url(r'song/(?P<pk>[0-9]+)/$', views.SongUpdate.as_view(), name='song-update'),
    url(r'song/(?P<pk>[0-9]+)/delete/$', views.SongDelete.as_view(), name='song-delete'),
]

movie/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Movie(models.Model):
    title = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    logo = models.FileField()
    
    def get_absolute_url(self):
        return reverse('movie:detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.title + ' ' + self.genre


class Actor(models.Model):
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    picture = models.FileField()
    is_favorite = models.BooleanField(default=False)
    
    def __str__(self):
        return self.name

song/models.py
from django.db import models
from django.core.urlresolvers import reverse

        
class Song(models.Model):
    title = models.CharField(max_length=50)
    genre = models.CharField(max_length=50)
    logo = models.FileField()
    
    def __str__(self):
        return self.title + ' ' + self.genre
        
    def get_absolute_url(self):
        return reverse('song:detail', kwargs={'pk': self.pk})
    
    def __str__(self):
        return self.title + ' ' + self.genre
        
        
class Artist(models.Model):
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    picture = models.FileField()
    is_favorite = models.BooleanField(default=False)
    def __str__(self):
        return self.name

keepyourfriendsclose/forms.py
from django.contrib.auth.models import User
from django import forms


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']

keepyourfriendsclose/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.contrib.auth import authenticate, login
from django.views import generic
from django.views.generic import View
from .forms import UserForm

class HomeView(generic.ListView):
    template_name = 'keepyourfriendsclose/home.html'
    
    def get_queryset(self):
        pass
        
class UserFormView(View):
    form_class = UserForm
    template_name = 'keepyourfriendsclose/registration_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})
        
    def post(self, request):
        form = self.form_class(request.POST)
        
        if form.is_valid():
            user = form.save(commit=False)
            
            # cleaned (normalied data)
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)
            
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home')
                    
        return render(request, self.template_name, {'form': form})

movie/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.views import generic
from .models import Movie


class HomeView(generic.ListView):
    template_name = 'movie/home.html'
    context_object_name = 'all_movies'
    
    def get_queryset(self):
        return Movie.objects.order_by('title')


class DetailView(generic.DetailView):
    model = Movie
    template_name = 'movie/detail.html'
    
    
class MovieCreate(CreateView):
    model = Movie
    fields = ['title', 'genre', 'logo']
 
 
class MovieUpdate(UpdateView):
    model = Movie
    fields = ['title', 'genre']
    
    
class MovieDelete(DeleteView):
    model = Movie
    success_url = reverse_lazy('movie:home')

song/views.py
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.views import generic
from .models import Song

class HomeView(generic.ListView):
    template_name = 'song/home.html'
    context_object_name = 'all_songs'
    
    def get_queryset(self):
        return Song.objects.order_by('title')

class DetailView(generic.DetailView):
    model = Song
    template_name = 'song/detail.html'
    

class SongCreate(CreateView):
    model = Song
    fields = ['title', 'genre', 'logo']
 
 
class SongUpdate(UpdateView):
    model = Song
    fields = ['title', 'genre', 'logo']
    
    
class SongDelete(DeleteView):
    model = Song
    success_url = reverse_lazy('song:home')

keepyourfriendsclose/templates/keepyourfriendsclose/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Keep Your Friends Close{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'movie/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class="container-fluid">
        
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Keeper</a>
            </div>
            
            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
            
                <ul class="nav navbar-nav">
                
                    <li class="">
                        <a href="{% url 'movie:home' %}">
                            <span class="glyphicon glyphicon-film aria-hidden="true"></span>&nbsp;Movies
                        </a>
                    </li>
                    
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                    
                </ul>
                
                
                <ul class="nav navbar-nav navbar-right">
                     <li class="">
                        <form class="navbar-form navbar-left" role="search" method="get" action="#">
                            <div class="form-group">
                                <input type="text" class="form-control" name="q" value="">
                            </div>
                            <button type="submit" class="btn btn-default">Search</button>
                        </form>
                    </li> 
                
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;{{ "Test"|default:"Logout" }}
                        </a>
                    </li>  
                    
                </ul>
                
            </div>
            
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    </body>
</html>

keepyourfriendsclose/templates/keepyourfriendsclose/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span> 
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

keepyourfriendsclose/templates/keepyourfriendsclose/home.html
{% extends 'keepyourfriendsclose/base.html' %}

{% block body %}
    <h1>This is what I like:<h1>
    <div class="row">
    
      <div class="col-sm-4 col-md-2">
        <div class="thumbnail">
          <img src="https://image.freepik.com/free-vector/movie-cinema-icons_23-2147495008.jpg" alt="Movies">
          <div class="caption">
            <p><a href="{% url 'movie:home' %}" class="btn btn-primary" role="button">Movies</a>
          </div>
        </div>
      </div>
      
      <div class="col-sm-4 col-md-2">
        <div class="thumbnail">
          <img src="https://image.freepik.com/free-vector/icons-flat-set-musical-instruments_23-2147492904.jpg" alt="Songs">
          <div class="caption">
            <p><a href="{% url 'song:home' %}" class="btn btn-primary" role="button">Songs</a>
          </div>
        </div>
      </div>
      
    </div>

{% endblock %}

keepyourfriendsclose/templates/keepyourfriendsclose/registration_form.html
{% extends 'keepyourfriendsclose/base.html' %}
{% block title %}Register{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class = "col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                <h3>Create a New Account</h3>
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'keepyourfriendsclose/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div> 
         </div>
     </div>
</div>
{% endblock %}

movie/templates/movie/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Movies{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'movie/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class="container-fluid">
        
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Keeper</a>
            </div>
            
            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'movie:home' %}">
                            <span class="glyphicon glyphicon-film aria-hidden="true"></span>&nbsp;Movies
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'movie:movie-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Movie
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>                   
                </ul>
            </div>
            
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    </body>
</html>

movie/templates/movie/detail.html
{% extends 'movie/base.html' %}
{% block title %}Movie Details{% endblock %}
{% block body %}
    <h1>Details</h1>
    <h2>{{ movie.title }}</h2>
    <h3>{{ movie.genre }}</h3>

        <h4>Actors</h4>
        {% for actor in movie.actor_set.all %}
                {{ actor.name }}
                {% if actor.is_favorite %}
                    <img src="http://findicons.com/files/icons/1620/crystal_project/22/knewstuff.png" />
                {% endif %}
                <br>
        {% endfor %}
        
    <a href="{% url 'movie:home' %}">Back to Home</a>
{% endblock %}

movie/templates/movie/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span> 
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

movie/templates/movie/home.html
{% extends 'movie/base.html' %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Movies -->
    <div class="row">
        <div class="col-sm-12">
        </div>
        {% if all_movies %}
            {% for movie in all_movies %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                    
                <!-- Album logo -->
                <a href="{% url 'movie:detail' movie.id %}">
                    <img src="{{ movie.logo.url }}" class="img-responsive">
                </a>
                
                <div class="caption">
                    <h4>{{ movie.title }}</h4>
                    <p>{{ movie.genre }}</p>

                <!-- View Details -->
                <a href="{% url 'movie:detail' movie.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                <!-- Delete Album -->
                <form action="{% url 'movie:movie-delete' movie.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="movie_id" value="{{ movie.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
             </li>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'movie:movie-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Movie
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
    <a href="{% url 'home' %}">Back to the Homepage</a>
{% endblock %}

movie/templates/movie/movie_form.html
{% extends 'movie/base.html' %}
{% block title %}Add a new Movie{% endblock %}
{% block movies_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class = "col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'movie/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div> 
         </div>
     </div>
</div>
{% endblock %}

song/templates/song/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Songs{% endblock %}</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" type="text/css" href="{% static 'song/style.css' %}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
</head>
<body>
    <nav class = "navbar navbar-inverse">
        <div class="container-fluid">
        
            <!-- Header -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}">Keeper</a>
            </div>
            
            <!-- Items -->
            <div class="collapse navbar-collapse" id="topNavBar">
                <ul class="nav navbar-nav">
                    <li class="">
                        <a href="{% url 'movie:home' %}">
                            <span class="glyphicon glyphicon-film aria-hidden="true"></span>&nbsp;Movies
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                </ul>
                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <input type="text" class="form-control" name="q" value="">
                    </div>
                    <button type="submit" class="btn btn-default">Search</button>
                </form>
                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                        <a href="{% url 'song:song-add' %}">
                            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add Song
                        </a>
                    </li>
                    <li class="">
                        <a href="{% url 'song:home' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                        </a>
                    </li>                   
                </ul>
            </div>
            
        </div>
    </nav>
    {% block body %}
    {% endblock %}
    </body>
</html>

song/templates/song/detail.html
{% extends 'song/base.html' %}
{% block title %}Song Details{% endblock %}
{% block body %}
    <h1>Details</h1>
    <h2>{{ song.title }}</h2>
    <h3>{{ song.genre }}</h3>

    {% for artist in song.artist_set.all %}
        {{ artist.name }}
        {% if artist.is_favorite %}
            <img src="http://findicons.com/files/icons/1620/crystal_project/22/knewstuff.png" />
        {% endif %}
        <br>
    {% endfor %}

    <a href="{% url 'song:home' %}">Back to Home</a>
{% endblock %}

song/templates/song/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span> 
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

song/templates/song/home.html
{% extends 'song/base.html' %}

{% block body %}
<div class="albums-container container-fluid">

    <!-- Songs -->
    <div class="row">
        <div class="col-sm-12">
        </div>
        {% if all_songs %}
            {% for song in all_songs %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                    
                <!-- Album logo -->
                <a href="{% url 'song:detail' song.id %}">
                    <img src="{{ song.logo.url }}" class="img-responsive" height="200" width="200">
                </a>
                
                <div class="caption">
                    <h4>{{ song.title }}</h4>
                    <p>{{ song.genre }}</p>

                <!-- View Details -->
                <a href="{% url 'song:detail' song.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                <!-- Delete Album -->
                <form action="{% url 'song:song-delete' song.id %}" method="post" style="display: inline;">
                    {% csrf_token %}
                    <input type="hidden" name="song_id" value="{{ song.id }}" />
                    <button type="submit" class="btn btn-default btn-sm">
                        <span class="glyphicon glyphicon-trash"></span>
                    </button>
                </form>
             </li>
                        </div>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
        {% else %}
            <div class="col-sm-12">
                <br>
                <a href="{% url 'song:song-add' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; Add a Song
                    </button>
                </a>
            </div>
        {% endif %}
    </div>
</div>
    <a href="{% url 'home' %}">Back to the Homepage</a>
{% endblock %}

song/templates/song/song_form.html
{% extends 'song/base.html' %}
{% block title %}Add a new Song{% endblock %}
{% block songs_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="row">
        <div class = "col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'song/form-template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div> 
         </div>
     </div>
</div>
{% endblock %}